apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.name }}-${{ values.suffix }}-stack
  title: ${{ values.name | title }} MongoDB Stack
  description: Complete MongoDB infrastructure stack including cluster, DNS, and database
  tags:
    - mongodb
    - infrastructure
    - golden-path
  annotations:
    backstage.io/managed-by-location: url:${{ values.repoUrl }}
spec:
  owner: ${{ values.owner | default('group:platform') | dump }}
  domain: platform-services
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-${{ values.suffix }}-mongodb
  title: ${{ values.name | title }} MongoDB Database
  description: MongoDB database instance
  annotations:
    backstage.io/managed-by-location: url:${{ values.repoUrl }}
  tags:
    - database
    - mongodb
    - crossplane
spec:
  type: database
  owner: ${{ values.owner | default('group:platform') | dump }}
  lifecycle: ${{ values.lifecycle | default('experimental') }}
  system: ${{ values.name }}-${{ values.suffix }}-stack
  dependsOn:
    - resource:default/${{ values.name }}-${{ values.suffix }}-cluster
    - resource:default/${{ values.name }}-${{ values.suffix }}-dns
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-${{ values.suffix }}-cluster
  title: ${{ values.name | title }} Kubernetes Cluster
  description: Kubernetes cluster for MongoDB
  annotations:
    backstage.io/managed-by-location: url:${{ values.repoUrl }}
  tags:
    - kubernetes
    - infrastructure
    - crossplane
spec:
  type: kubernetes-cluster
  owner: ${{ values.owner | default('group:platform') | dump }}
  lifecycle: ${{ values.lifecycle | default('experimental') }}
  system: ${{ values.name }}-${{ values.suffix }}-stack
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-${{ values.suffix }}-dns
  title: ${{ values.name | title }} DNS Record
  description: DNS record for MongoDB access
  annotations:
    backstage.io/managed-by-location: url:${{ values.repoUrl }}
  tags:
    - dns
    - networking
    - crossplane
spec:
  type: dns-record
  owner: ${{ values.owner | default('group:platform') | dump }}
  lifecycle: ${{ values.lifecycle | default('experimental') }}
  system: ${{ values.name }}-${{ values.suffix }}-stack
  dependsOn:
    - resource:default/${{ values.name }}-${{ values.suffix }}-cluster